### ISSUE TITLE
Error ‘-1’ will be reported when loading any addon

### ISSUE THREAD

**Issue by Priul** [LiteLDev/LegacyAddonsManager#5]
### Describe the bug

none

### To Reproduce

none

### Expected behavior

none

### Screenshots

![39805d2d-2a6e-4f96-bbf3-96ce9594e91a](https://github.com/user-attachments/assets/03b0f85a-c247-453e-8690-e6a9b2713f8f)

### Platform

Windows 11

### BDS Version

1.21.3.01

### LeviLamina Version

0.13.5

### Version

0.5.1

**Comment by ShrBox** [comment]
Are you using lip to install this mod or just download from release then install it manually?
If you installed this mod manually, you have to download 7-zip by yourself then put 7za.exe to BDS path.
